### ISSUE TITLE
Isolation level with PostgreSQL

### ISSUE THREAD

**Issue by Aliance** [facile-it/paraunit-testcase#10] opened 2017-01-12 07:38 UTC
The main disadvantage of this approach is isolation levels into PostgreSQL: as we run test cases into the transactions, we can not read just written data (dirty read), because of PostgreSQL has not have Read uncommitted level.

So if you test for example creation of some entity, you can not test real getting of this entity in the same test case.

**Comment by Jean85** [comment] 2017-01-12 08:34
Thanks for your input!

Looking at [Doctrine's documentation](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/transactions.html) about it, it seems that every vendor that they support uses at least `Connection::TRANSACTION_READ_COMMITTED`, which is the one used by `ParaunitFunctionalTestCase`. 

~~Are you sure that this isn't working? I'm not sure about Doctrine's inner working, but maybe they emulate that for Postgre.~~ [EDIT] found the docs about it: https://www.postgresql.org/docs/9.1/static/transaction-iso.html

**Comment by Aliance** [comment] 2017-01-12 08:58
You're right, PostgreSQL does not support Read Uncommitted level at all:
> When you select the level Read Uncommitted you really get Read Committed, and phantom reads are not possible in the PostgreSQL implementation of Repeatable Read, so the actual isolation level might be stricter than what you select.

So there no dirty read in PostgreSQL, so developers can't test getting of just inserting entities :(

**Comment by Jean85** [comment] 2017-01-12 09:33
That's bad... Damn, I don't see a workaround, it's a hard limitation.

**Comment by dxops** [comment] 2017-01-12 11:45
>The Repeatable Read isolation level only sees data committed before the transaction began; it never sees either uncommitted data or changes committed during transaction execution by concurrent transactions. (**However, the query does see the effects of previous updates executed within its own transaction, even though they are not yet committed.**)

According to https://www.postgresql.org/docs/9.6/static/transaction-iso.html

Same works for MySQL according to https://dev.mysql.com/doc/refman/5.7/en/innodb-transaction-isolation-levels.html

Explicit `$conn->setAutoCommit(false)` is a good option too.

**Comment by Jean85** [comment] 2017-01-12 14:59
The issue is in the fact that Doctrine does not commit until the last level of transaction is committed, see [here](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/transactions.html):

> Whenever the nesting level transitions from 0 to 1, beginTransaction() is invoked on the underlying driver connection and whenever the nesting level transitions from 1 to 0, commit() or rollBack() is invoked [...]

> What this means is that transaction control is basically passed to code higher up in the call stack and the inner transaction block is ignored, [...]. Do not confuse this with “real” nested transactions or savepoints. These are not supported by Doctrine. There is always only a single, real database transaction.

So we are out of the scope of what you quoted, unfortunately...

**Comment by dxops** [comment] 2017-01-12 15:10
There is no need to commit at all. You just do START TRANSACTION - ROLLBACK for each test case. Check https://github.com/orocrm/platform/blob/master/src/Oro/Component/Testing/DbIsolationExtension.php and https://github.com/orocrm/platform/tree/master/src/Oro/Component/Testing/Doctrine

**Comment by Jean85** [comment] 2017-01-12 15:57
That's exactly what this lib does. But, since no commit is done, with PgSQL you can't re-query the DB to do assertions during your tests, since you cannot read what your test (or class under test) has just written.

**Comment by dxops** [comment] 2017-01-12 16:01
~~You can, using Repeatable Read isolation level~~

Let me clarify. PostgreSQL behaves almost same like MySQL.

You can find pretty good isolation explanation here https://adayinthelifeof.nl/2010/12/20/innodb-isolation-levels/

That works well for updates. Inserted data in the transaction always available for itself (See logs below).

So in our case, there is no difference between REPEATABLE READ and READ COMMITTED because we don't have commits at all!

> So if you test for example creation of some entity, you can not test real getting off this entity in the same test case.

That's because isolation works for [each test in test case](https://github.com/facile-it/paraunit-testcase/blob/master/src/ParaunitTestCase/TestCase/ParaunitFunctionalTestCase.php#L55) and it's not possible to check entity in the second test if it was created in the first one. Just check it in the same test

PostgreSQL + REPEATABLE READ
```
dev=# BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ ;
BEGIN
dev=# select * from test;
 val
-----
   8
   8
(2 rows)

dev=# INSERT INTO test VALUES (11);
INSERT 0 1
dev=# select * from test;
 val
-----
   8
   8
  11
(3 rows)
```

PostgreSQL + READ COMMITTED
```
dev=# BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED ;
BEGIN
dev=# select * from test;
 val
-----
   8
   8
(2 rows)

dev=# INSERT INTO test VALUES (11);
INSERT 0 1
dev=# select * from test;
 val
-----
   8
   8
  11
(3 rows)
```

MySQL + REPEATABLE READ
```
mysql> SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Query OK, 0 rows affected (0.00 sec)

mysql> START TRANSACTION;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from test;
+------+
| val  |
+------+
|    8 |
|    8 |
+------+
2 rows in set (0.00 sec)

mysql> INSERT INTO test VALUES (10);
Query OK, 1 row affected (0.00 sec)

mysql> select * from test;
+------+
| val  |
+------+
|    8 |
|    8 |
|   10 |
+------+
3 rows in set (0.00 sec)
```

MySQL + READ COMMITTED
```
mysql> SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
Query OK, 0 rows affected (0.00 sec)

mysql> START TRANSACTION;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from test;
+------+
| val  |
+------+
|    8 |
|    8 |
+------+
2 rows in set (0.00 sec)

mysql> INSERT INTO test VALUES (10);
Query OK, 1 row affected (0.01 sec)

mysql> select * from test;
+------+
| val  |
+------+
|    8 |
|    8 |
|   10 |
+------+
3 rows in set (0.00 sec)
```

**Comment by Jean85** [comment] 2017-01-13 00:56
Oh well, this seems counterintuitive, but you are right!
@Aliance do you have a counter example? It seems to me that this should work with PGSQL with no issues! Are you sure that you didn't forget to refresh the entity?

**Comment by dxops** [comment] 2017-01-13 10:32
@Jean85 BTW, I feel like we should run test cases from one namespace in the same process one by one because with update queries all transaction will delay each other time to time. The more update queries to the same table we have, the more time we will spend to wait for other transactions.

**Comment by Jean85** [comment] 2017-01-13 13:17
I don't think that splitting by namespace could be useful, it depends too much on how the code is organized.

In reality, the number of fixtures is a much more impactful parameter in this matter.

**Closed as completed** 2017-01-25 19:35 UTC
